WITH RECURSIVE A(ID) AS (SELECT 2 UNION ALL SELECT ID + 1 FROM A WHERE ID < 1000)

SELECT GROUP_CONCAT(X SEPARATOR '&') AS Y
FROM (SELECT A.ID AS X, COUNT(*) AS Y
     FROM A
     INNER JOIN A AS B ON A.ID >= B.ID
     WHERE MOD(A.ID, B.ID) = 0 GROUP BY A.ID) AS NT
WHERE Y < 2
ORDER BY X;
