SELECT Start_Date, MIN(End_Date)
FROM
    (SELECT Start_Date
    FROM Projects
    WHERE Start_Date NOT IN (SELECT END_DATE FROM PROJECTS)) AS A,
    (SELECT END_DATE
    FROM PROJECTS
    WHERE END_DATE NOT IN (SELECT START_DATE FROM PROJECTS)) AS B

WHERE START_DATE < END_DATE
GROUP BY START_DATE
ORDER BY DATEDIFF(Start_Date, MIN(End_Date)) DESC, START_DATE
